# terminal font
# https://www.nerdfonts.com/font-downloads

gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"



# Plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set-option -g default-shell /bin/zsh

set -g history-limit 10000
set-option -g repeat-time 1000
set -g status-position top
# Reaching for '0' key is HARD
set -g base-index 1
set -g pane-base-index 1
set -g mouse on

# remap prefix key to Ctrl+a
unbind C-a
set -g prefix C-a

# detach from current session
bind-key C-d detach-client

# reload tmux config
unbind r
bind r source-file ~/.tmux.conf \; display "Reloading config..."

# Splits

# vertical splits pane
unbind %
unbind v
bind \\ split-window -h -c "#{pane_current_path}"

# horizontal split pane
unbind h
bind - split-window -v -c "#{pane_current_path}"

# new window
bind c new-window -c "#{pane_current_path}"

unbind p
bind-key p display-popup -d "#{pane_current_path}" -w 70% -h 50% -E 'python3'
unbind b
bind-key b display-popup -d "#{pane_current_path}" -w 70% -h 50% -E 'bash'
unbind g
bind-key g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E 'lazygit'
unbind C-c
bind C-c display-popup -d "#{pane_current_path}" -w 70% -h 50% -E '~/.local/bin/copilot'
bind-key > resize-pane -R 5 \; switch-client -T "resize-pane"
bind-key < resize-pane -L 5 \; switch-client -T "resize-pane"
bind-key + resize-pane -D 5 \; switch-client -T "resize-pane"
bind-key - resize-pane -U 5 \; switch-client -T "resize-pane"



# Close pane
#unbind w
#unbind C-w
#bind-key w kill-pane
#bind-key C-w kill-pane

#
setw -g monitor-activity on
setw -g mode-keys vi
set -g visual-activity on
set -g set-titles on  # show activity on terminal title
set -g automatic-rename off


# tmux catppuccin theme defaults
#set -g @plugin 'catppuccin/tmux#v2.1.3'
#set -g @catppuccin_flavour 'mocha' # latte, frappe, macchiato, mocha

#run ~/.tmux/plugins/catppuccin/catppuccin.tmux

set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

#set -g @catppuccin_window_status_style "underscore"
#set -g @catppuccin_window_text "#W"
#set -g @catppuccin_window_current_text "#W"
#set -g @catppuccin_window_default_text "#W"

#set -g status-right-length 100
#set -g status-left-length 100
#set -g status-left "#{E:@catppuccin_status_window}"
#set -g status-left "#{E:@catppuccin_status_window}"
#set -g status-right "#{E:@catppuccin_status_application}"
#set -ag status-right "#{E:@catppuccin_status_session}"
##set -ag status-right "#{E:@catppuccin_status_uptime}"


# Status bar customization
set -g status-justify centre
set -g status-left-length 80
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold] #S #[fg=${gray_light},nobold] | "
set -g window-status-current-format "#[fg=${cyan_soft},bold]  #[underscore]#I:#W#[nounderscore]#{?window_zoomed_flag, 󰍋 ,}"
set -g window-status-format " #I:#W"
set -g message-style "fg=${gray_light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${green_soft}"


run '~/.tmux/plugins/tpm/tpm'
