# Nginx dockerfile

FROM centos:centos6

MAINTAINER Akash Shende <akash@anoosmar.com>

RUN yum --verbose -y --disableplugin=fastestmirror update &&\
    yum -y install epel-release &&\
    yum -y install nginx

